name: Rust CI

on:
  push:
    branches:
      - main
    paths:
      - "src-tauri/**"
      - ".github/workflows/rust.yml"
  pull_request:
    branches:
      - main
    paths:
      - "src-tauri/**"
      - ".github/workflows/rust.yml"

jobs:
  ci:
    name: Lint Rust
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
      DATABASE_URL: "sqlite://data.db"
    defaults:
      run:
        working-directory: ./src-tauri

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "main"
          cache-on-failure: true

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libssl-dev
          cargo install sqlx-cli --no-default-features --features sqlite

      - name: Setup database
        run: |
          cargo sqlx db create
          cargo sqlx migrate run --source ./migrations

      - name: lint
        run: cargo clippy -- -D warnings

      - name: fmt
        run: cargo fmt --all -- --check
